### ISSUE TITLE
DG Review for T16-4

### ISSUE THREAD

**Issue by kaiwen98** [AY2122S1-CS2113-T16-4/tp#48]
**1. Not sure why the application becomes active before it is called. If this is not the case, ensure that the activation bar extends after the operation arrow.**
![image](https://user-images.githubusercontent.com/57187325/139215620-f6b7a2fc-4156-4cb9-be43-99f197514105.png)

**2. Not sure if the right syntax is followed. There should not be an underline for the actor name.**
![image](https://user-images.githubusercontent.com/57187325/139215939-30959340-ea4e-4bad-a310-7c275c8ec622.png)

**3. Not sure how datastring is passed from LoadableManager with it remaining active. If this is not the case, ensure that the activation bar ends where it is appropriate.**
![image](https://user-images.githubusercontent.com/57187325/139216253-956d48fc-c4e4-4b86-a635-f532e68a1912.png)

**4. Suggestiont to add comments here so as to elaborate the loop condition.**
![image](https://user-images.githubusercontent.com/57187325/139217852-f3841370-45e8-4d9a-9d07-7d12c799b8bd.png)

**Comment by Journeyman1998** [comment]
Thanks for the comments Kai Wen, I will make the changes to the DG.
